import { useEffect, useMemo, useState } from 'react'
import { alertsAPI } from '../services/api'
import { EmptyState, ErrorState, SkeletonPage } from '../components/UI'
import { canonicalDeviceId, dataSourceLabel, recommendedAction } from '../utils/presentation'

export default function Alerts() {
  const [alerts, setAlerts] = useState([])
  const [status, setStatus] = useState('all')
  const [severity, setSeverity] = useState('all')
  const [search, setSearch] = useState('')
  const [visible, setVisible] = useState(25)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [toast, setToast] = useState('')

  const load = async () => { setLoading(true); try { setAlerts(await alertsAPI.getAll({ limit: 100 })); setError('') } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 3000); return () => clearTimeout(timer) } }, [toast])

  const filtered = useMemo(() => alerts.filter(alert => { const alertStatus = alert.status || (alert.resolved ? 'resolved' : 'active'); const text = `${canonicalDeviceId(alert.device_id || alert.deviceId)} ${alert.message} ${recommendedAction(alert)}`.toLowerCase(); return (status === 'all' || alertStatus === status) && (severity === 'all' || alert.severity === severity) && text.includes(search.toLowerCase()) }).sort((a, b) => new Date(b.timestamp || b.createdAt || 0) - new Date(a.timestamp || a.createdAt || 0)), [alerts, status, severity, search])
  const stats = { total: alerts.length, active: alerts.filter(a => (a.status || 'active') === 'active' && !a.resolved).length, critical: alerts.filter(a => a.severity === 'critical').length, resolvedToday: alerts.filter(a => a.resolved && new Date(a.resolvedAt || a.timestamp || 0).toDateString() === new Date().toDateString()).length }
  const acknowledge = async (alert) => { const updated = await alertsAPI.acknowledge(alert.id, 'system'); setAlerts(items => items.map(item => item.id === alert.id ? { ...item, ...updated } : item)); setToast('Alert acknowledged and assigned to ICT support workflow') }
  const resolve = async (alert) => { const updated = await alertsAPI.resolve(alert.id, 'system', 'Resolved from alert management dashboard'); setAlerts(items => items.map(item => item.id === alert.id ? { ...item, ...updated } : item)); setToast('Alert resolved and closed') }

  if (loading) return <SkeletonPage variant="table" />
  if (error) return <ErrorState message={error} onRetry={load} />

  return <div className="alerts-page"><div className="page-header"><div><h3>Predictive Alert Management</h3><p>Alerts generated from telemetry thresholds and Random Forest fault-prone predictions.</p></div><span className="source">{dataSourceLabel()}</span></div>{toast && <div className="toast">{toast}</div>}<section className="stats"><Card title="Total Alerts" value={stats.total} /><Card title="Active Alerts" value={stats.active} danger /><Card title="Critical Alerts" value={stats.critical} danger /><Card title="Resolved Today" value={stats.resolvedToday} /></section><section className="filters"><div>{['all','active','acknowledged','resolved'].map(item => <button className={status === item ? 'active' : ''} onClick={() => setStatus(item)} key={item}>{item}</button>)}</div><select value={severity} onChange={event => setSeverity(event.target.value)}><option value="all">All Severities</option><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select><input placeholder="Search device, message, or action" value={search} onChange={event => setSearch(event.target.value)} /></section><section className="panel"><table><thead><tr><th>Severity</th><th>Asset</th><th>Fault Signal</th><th>Message</th><th>Recommended Action</th><th>Status</th><th>Time</th><th>Actions</th></tr></thead><tbody>{filtered.slice(0, visible).map(alert => { const alertStatus = alert.status || (alert.resolved ? 'resolved' : 'active'); return <tr className={alert.severity} key={alert.id}><td><span className={`chip ${alert.severity}`}>{alert.severity}</span></td><td>{canonicalDeviceId(alert.device_id || alert.deviceId)}</td><td>{alert.alert_type || alert.type || 'predictive'}</td><td>{alert.message}</td><td>{recommendedAction(alert)}</td><td><span className={`chip ${alertStatus}`}>{alertStatus}</span></td><td>{formatTime(alert.timestamp || alert.createdAt)}</td><td>{alertStatus === 'active' && <button onClick={() => acknowledge(alert)}>Acknowledge</button>}{alertStatus === 'acknowledged' && <button onClick={() => resolve(alert)}>Resolve</button>}</td></tr> })}</tbody></table>{filtered.length === 0 && <EmptyState title="No alerts match the current filters" detail="Try another status, severity, or device search term." />}{visible < filtered.length && <button onClick={() => setVisible(value => value + 25)}>Load More</button>}</section><style>{styles}</style></div>
}
function Card({ title, value, danger }) { return <div className="card"><span>{title}</span><strong className={danger ? 'dangerText' : ''}>{value}</strong></div> }
function formatTime(value) { return value ? new Date(value).toLocaleString() : '-' }
const styles = `.spinner{text-align:center;padding:50px}.error{background:#fee2e2;color:#991b1b;padding:16px;border-radius:10px}.page-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:20px}.page-header h3{font-size:26px;margin:0}.page-header p{color:#6b7280}.source{font-size:12px;color:#2b6e60;background:#ecfdf5;border:1px solid #bbf7d0;border-radius:999px;padding:7px 11px;white-space:nowrap}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin-bottom:18px}.card,.filters,.panel{background:white;border-radius:14px;box-shadow:0 2px 8px rgba(0,0,0,.08);padding:18px}.card span{display:block;color:#6b7280}.card strong{font-size:32px;color:#111827}.dangerText{color:#dc2626!important}.filters{display:flex;gap:12px;align-items:center;margin-bottom:18px;flex-wrap:wrap}.filters div{display:flex;gap:8px}button{background:#16a34a;color:white;border:0;border-radius:9px;padding:9px 12px;font-weight:800;cursor:pointer}button.active{background:#0f3460}select,input{padding:10px;border:1px solid #d1d5db;border-radius:9px}input{min-width:260px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #e5e7eb;vertical-align:top}th{color:#6b7280;font-size:12px;text-transform:uppercase}tr.critical{background:#fff7f7}tr.warning{background:#fffbeb}tr.info{background:#eff6ff}.chip{display:inline-block;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:800;text-transform:capitalize}.critical,.active{background:#fee2e2;color:#991b1b}.warning,.acknowledged{background:#fef3c7;color:#92400e}.info{background:#dbeafe;color:#1e40af}.resolved{background:#dcfce7;color:#166534}.empty{text-align:center;padding:30px;color:#6b7280}.toast{position:fixed;right:24px;bottom:24px;background:#16a34a;color:white;padding:14px 18px;border-radius:10px;box-shadow:0 6px 18px rgba(0,0,0,.18);z-index:10}`
