import { Link } from 'react-router-dom'
import { devicesAPI } from '../services/api'
import { useApiData } from '../services/useApiData'
import { EmptyState, ErrorState, SkeletonPage } from '../components/UI'
import { canonicalDeviceId, canonicalDeviceName, dataSourceLabel, predictionLabel } from '../utils/presentation'

export default function Devices() {
  const { data: devices, loading, error } = useApiData(devicesAPI.getAll, 'devices')

  if (loading) return <SkeletonPage variant="table" />
  if (error) return <ErrorState message={error} />

  return <div className="devices-page"><div className="page-header"><div><h3>Monitored ICT Assets</h3><p className="page-subtitle">Standardized campus infrastructure inventory used for telemetry, prediction, and alerting.</p></div><span className="source">{dataSourceLabel()}</span></div><div className="filters"><input aria-label="Asset search" placeholder="Search assets by ID, type, status, or location" readOnly /><span className="ui-pill">{devices.length} registered assets</span></div>{devices.length === 0 ? <EmptyState title="No monitored assets found" detail="Register or seed campus ICT devices before running telemetry polling." /> : <div className="table-container"><table className="data-table"><thead><tr><th>Asset ID</th><th>Canonical Name</th><th>Type</th><th>Status</th><th>Prediction State</th><th>Location</th><th>Action</th></tr></thead><tbody>{devices.map(device => <tr key={device.id} className="click-row"><td><strong>{canonicalDeviceId(device)}</strong></td><td><Link to={`/devices/${device.id}`}>{canonicalDeviceName(device)}</Link></td><td>{device.type}</td><td><span className={`status status-${device.status || 'online'}`}>{device.status || 'online'}</span></td><td><span className={`prediction ${(device.predictionState || device.prediction_state) === 'fault_prone' ? 'risk' : 'normal'}`}>{predictionLabel(device.predictionState || device.prediction_state || 'normal')}</span></td><td>{device.location || 'GZU Campus'}</td><td><Link className="view-button" to={`/devices/${device.id}`}>View Telemetry</Link></td></tr>)}</tbody></table></div>}<style>{styles}</style></div>
}
const styles = `.loading{text-align:center;padding:40px;color:#666}.error-box{background:#f8d7da;color:#721c24;padding:16px;border-radius:8px}.page-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px}.page-header h3{font-size:26px;margin:0;color:#111827}.page-subtitle{color:#666;font-size:14px;margin-top:6px}.source{font-size:12px;color:#2b6e60;background:#ecfdf5;border:1px solid #bbf7d0;border-radius:999px;padding:7px 11px;white-space:nowrap}.table-container{background:white;border-radius:14px;box-shadow:0 2px 8px rgba(0,0,0,.1);overflow-x:auto}.data-table{width:100%;border-collapse:collapse}.data-table th{text-align:left;padding:16px;font-size:12px;color:#6b7280;border-bottom:2px solid #f0f0f0;text-transform:uppercase}.data-table td{padding:16px;font-size:14px;border-bottom:1px solid #f0f0f0}.data-table strong{color:#2b6e60}.click-row:hover{background:#f8fafc}.status,.prediction,.view-button{display:inline-block;padding:6px 12px;border-radius:20px;font-size:12px;font-weight:700;text-transform:capitalize}.status-online,.normal{background:#d4edda;color:#155724}.status-warning{background:#fff3cd;color:#856404}.status-offline,.risk{background:#f8d7da;color:#721c24}.view-button{background:#dbeafe;color:#1e40af;text-decoration:none}`
