import { useEffect, useMemo, useState } from 'react'
import { devicesAPI, scenariosAPI } from '../services/api'

export default function Scenarios() {
  const [scenarios, setScenarios] = useState([])
  const [devices, setDevices] = useState([])
  const [runs, setRuns] = useState([])
  const [selected, setSelected] = useState(null)
  const [deviceId, setDeviceId] = useState('')
  const [loading, setLoading] = useState(true)
  const [running, setRunning] = useState(false)
  const [error, setError] = useState('')

  const load = async () => {
    setLoading(true)
    try { const [scenarioData, deviceData, runData] = await Promise.all([scenariosAPI.getAll(), devicesAPI.getAll(), scenariosAPI.getRuns()]); setScenarios(scenarioData); setDevices(deviceData); setRuns(runData); setDeviceId(deviceData[0]?.id || '') } catch (err) { setError(err.message) } finally { setLoading(false) }
  }
  useEffect(() => { load() }, [])
  const stats = useMemo(() => { const total = runs.length; const pass = runs.filter(run => run.result === 'pass').length; const fail = runs.filter(run => run.result === 'fail').length; const avg = total ? runs.reduce((sum, run) => sum + (run.prediction?.confidence || 0), 0) / total : 0; return { total, pass, fail, avg } }, [runs])
  const expectedClass = scenario => (`${scenario.id} ${scenario.name}`.toLowerCase().includes('normal') ? 'normal' : 'fault_prone')
  const runScenario = async () => { const device = devices.find(item => item.id === deviceId) || devices[0]; if (!selected || !device) return; setRunning(true); try { await scenariosAPI.runAndPredict(selected.id, device.id, device.type || 'server', 10); setSelected(null); await load() } finally { setRunning(false) } }

  if (loading) return <div className="spinner">Loading scenario validation suite...</div>
  if (error) return <div className="error">Unable to load scenarios: {error}<button onClick={load}>Retry</button></div>

  return <div className="scenarios-page"><div className="page-header"><h3>Scenarios</h3><p>Validation suite for prediction correctness</p></div><section className="stats"><Card title="Total Runs" value={stats.total} /><Card title="Pass" value={`${stats.pass} (${stats.total ? ((stats.pass / stats.total) * 100).toFixed(0) : 0}%)`} /><Card title="Fail" value={`${stats.fail} (${stats.total ? ((stats.fail / stats.total) * 100).toFixed(0) : 0}%)`} /><Card title="Average Confidence" value={`${(stats.avg * 100).toFixed(1)}%`} /></section><section className="grid">{scenarios.map(scenario => { const last = runs.find(run => run.scenarioId === scenario.id); return <div className="scenario-card" key={scenario.id}><h4>{scenario.name}</h4><span className="badge blue">{scenario.scenario_type}</span><p>{scenario.description}</p><span className="badge green">Expected: {expectedClass(scenario)}</span>{last && <p>Last run: <strong className={last.result === 'pass' ? 'passText' : 'failText'}>{last.result}</strong></p>}<button onClick={() => { setSelected(scenario); setDeviceId(devices[0]?.id || '') }}>Run and Predict</button></div> })}</section>{selected && <section className="modal"><div className="dialog"><h4>Run {selected.name}</h4><label>Target Device<select value={deviceId} onChange={event => setDeviceId(event.target.value)}>{devices.map(device => <option value={device.id} key={device.id}>{device.name || device.id} ({device.type})</option>)}</select></label><div className="actions"><button onClick={runScenario} disabled={running}>{running ? 'Running...' : 'Run'}</button><button className="cancel" onClick={() => setSelected(null)}>Cancel</button></div></div></section>}<section className="panel"><h4>Run History</h4><table><thead><tr><th>Scenario</th><th>Device</th><th>Expected</th><th>Predicted</th><th>Result</th><th>Confidence</th><th>Timestamp</th></tr></thead><tbody>{runs.map(run => <tr key={run.id || run.runId}><td>{run.scenarioId}</td><td>{run.deviceId}</td><td>{run.expectedClass}</td><td>{run.prediction?.predictedClass}</td><td><span className={`badge ${run.result === 'pass' ? 'green' : 'red'}`}>{run.result}</span></td><td>{((run.prediction?.confidence || 0) * 100).toFixed(1)}%</td><td>{formatTime(run.createdAt)}</td></tr>)}</tbody></table>{runs.length === 0 && <div className="empty">No scenario runs yet. Run a scenario to validate the model.</div>}</section><style>{styles}</style></div>
}
function Card({ title, value }) { return <div className="card"><span>{title}</span><strong>{value}</strong></div> }
function formatTime(value) { return value ? new Date(value).toLocaleString() : '-' }
const styles = `.spinner{text-align:center;padding:50px}.error{background:#fee2e2;color:#991b1b;padding:16px;border-radius:10px}.page-header{margin-bottom:20px}.page-header h3{font-size:26px;margin:0}.page-header p{color:#6b7280}.stats,.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin-bottom:18px}.card,.scenario-card,.panel,.dialog{background:white;border-radius:14px;box-shadow:0 2px 8px rgba(0,0,0,.08);padding:20px}.card span{display:block;color:#6b7280}.card strong{font-size:30px;color:#16a34a}.badge{display:inline-block;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:800;margin:3px}.green{background:#dcfce7;color:#166534}.red{background:#fee2e2;color:#991b1b}.blue{background:#dbeafe;color:#1e40af}.passText{color:#16a34a}.failText{color:#dc2626}button{background:#16a34a;color:white;border:0;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}.cancel{background:#6b7280}.modal{position:fixed;inset:0;background:rgba(0,0,0,.35);display:grid;place-items:center;z-index:10}.dialog{width:min(460px,90vw)}label span,label{display:block;color:#374151}select{width:100%;padding:10px;margin:8px 0 14px;border:1px solid #d1d5db;border-radius:9px}.actions{display:flex;gap:10px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #e5e7eb}th{color:#6b7280;font-size:12px;text-transform:uppercase}.empty{text-align:center;padding:28px;color:#6b7280}`
