import { telemetryAPI } from '../services/api'
import { useApiData } from '../services/useApiData'
import { EmptyState, ErrorState, SkeletonPage } from '../components/UI'
import { canonicalDeviceId, dataSourceLabel } from '../utils/presentation'

export default function Telemetry() {
  const { data: telemetry, loading, error } = useApiData(telemetryAPI.getAll, 'telemetry')

  if (loading) return <SkeletonPage variant="table" />
  if (error) return <ErrorState message={error} />

  return <div className="telemetry-page"><div className="page-header"><div><h3>Telemetry Signal Monitor</h3><p className="page-subtitle">Raw monitoring readings that feed observation windows, model prediction, and alert generation.</p></div><span className="source">{dataSourceLabel()}</span></div><section className="flow"><strong>Device Reading</strong><span>→</span><strong>Telemetry Window</strong><span>→</span><strong>Random Forest Prediction</strong><span>→</span><strong>Alert Workflow</strong></section>{telemetry.length === 0 ? <EmptyState title="No telemetry readings available" detail="Run a telemetry poll to collect monitoring signals for the historical test dataset." /> : <div className="table-container"><table className="data-table"><thead><tr><th>Reading ID</th><th>Asset</th><th>Signal</th><th>Value</th><th>Unit</th><th>Interpretation</th></tr></thead><tbody>{telemetry.map(tel => { const value = Number(tel.metric_value || 0); return <tr key={tel.id}><td>{tel.id}</td><td>{canonicalDeviceId(tel.device_id)}</td><td>{formatMetric(tel.metric_name)}</td><td className="metric-value">{value.toFixed(1)}</td><td>{tel.unit}</td><td><span className={`state ${stateFor(tel.metric_name, value)}`}>{stateFor(tel.metric_name, value)}</span></td></tr> })}</tbody></table></div>}<style>{styles}</style></div>
}
function formatMetric(value = '') { return String(value).replace(/_/g, ' ').replace(/\b\w/g, char => char.toUpperCase()) }
function stateFor(metric = '', value = 0) { const key = metric.toLowerCase(); if (key.includes('packet') && value > 5) return 'critical'; if (key.includes('latency') && value > 60) return 'critical'; if (key.includes('cpu') && value > 75) return 'warning'; if (key.includes('memory') && value > 78) return 'warning'; return 'normal' }
const styles = `.loading{text-align:center;padding:40px;color:#666}.error-box{background:#f8d7da;color:#721c24;padding:16px;border-radius:8px}.page-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px}.page-header h3{font-size:26px;margin:0;color:#111827}.page-subtitle{color:#666;font-size:14px;margin-top:6px}.source{font-size:12px;color:#2b6e60;background:#ecfdf5;border:1px solid #bbf7d0;border-radius:999px;padding:7px 11px;white-space:nowrap}.flow{display:flex;gap:12px;align-items:center;flex-wrap:wrap;background:white;border-radius:14px;box-shadow:0 2px 8px rgba(0,0,0,.08);padding:16px;margin-bottom:18px}.flow strong{color:#2b6e60}.flow span{color:#6b7280}.table-container{background:white;border-radius:12px;box-shadow:0 2px 8px rgba(0,0,0,.1);overflow-x:auto}.data-table{width:100%;border-collapse:collapse}.data-table th{text-align:left;padding:16px;font-size:12px;color:#666;border-bottom:2px solid #f0f0f0;text-transform:uppercase}.data-table td{padding:16px;font-size:14px;border-bottom:1px solid #f0f0f0}.metric-value{font-weight:800;color:#0f3460}.state{display:inline-block;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:800;text-transform:capitalize}.normal{background:#dcfce7;color:#166534}.warning{background:#fef3c7;color:#92400e}.critical{background:#fee2e2;color:#991b1b}`
