from datetime import datetime, timedelta

now = datetime.now

SEED_DATA = {
    "users": [
        {
            "id": "user-001",
            "email": "researcher@infrasight.local",
            "display_name": "InfraSight Researcher",
            "role": "analyst",
            "organisation": "Dissertation Lab",
            "created_at": now(),
        },
        {
            "id": "user-002",
            "email": "operator@infrasight.local",
            "display_name": "Infrastructure Operator",
            "role": "operator",
            "organisation": "ICT Operations",
            "created_at": now(),
        },
    ],
    "devices": [
        {
            "id": "dev-001",
            "name": "Core-Router-01",
            "type": "router",
            "status": "online",
            "location": "Data Center A",
            "vendor": "Cisco",
            "model": "ISR-4451",
            "criticality": "high",
            "ip_address": "10.10.0.1",
            "last_seen": now(),
        },
        {
            "id": "dev-002",
            "name": "Access-Switch-07",
            "type": "switch",
            "status": "online",
            "location": "Campus Block B",
            "vendor": "Aruba",
            "model": "2930F",
            "criticality": "medium",
            "ip_address": "10.10.7.2",
            "last_seen": now(),
        },
        {
            "id": "dev-003",
            "name": "Virtualization-Host-03",
            "type": "server",
            "status": "warning",
            "location": "Data Center B",
            "vendor": "Dell",
            "model": "PowerEdge R750",
            "criticality": "high",
            "ip_address": "10.20.0.13",
            "last_seen": now(),
        },
    ],
    "device_status": [
        {
            "id": "status-001",
            "device_id": "dev-001",
            "availability": 99.98,
            "cpu_usage": 41.3,
            "memory_usage": 54.2,
            "packet_loss": 0.02,
            "latency_ms": 8.4,
            "recorded_at": now(),
        },
        {
            "id": "status-002",
            "device_id": "dev-003",
            "availability": 98.42,
            "cpu_usage": 89.5,
            "memory_usage": 82.1,
            "packet_loss": 0.3,
            "latency_ms": 18.7,
            "recorded_at": now(),
        },
    ],
    "alerts": [
        {
            "id": "alert-001",
            "device_id": "dev-003",
            "severity": "warning",
            "message": "Sustained CPU saturation indicates elevated failure risk",
            "alert_type": "performance",
            "resolved": False,
            "timestamp": now(),
        },
        {
            "id": "alert-002",
            "device_id": "dev-001",
            "severity": "info",
            "message": "Firmware maintenance window recommended within 14 days",
            "alert_type": "maintenance",
            "resolved": False,
            "timestamp": now(),
        },
    ],
    "predictions": [
        {
            "id": "pred-001",
            "device_id": "dev-003",
            "prediction_type": "failure",
            "probability": 0.75,
            "time_to_failure": 72,
            "confidence": 0.85,
            "model_version": "pm-baseline-v2",
            "top_factors": ["cpu_usage", "thermal_trend", "historical_incidents"],
            "timestamp": now(),
        },
        {
            "id": "pred-002",
            "device_id": "dev-001",
            "prediction_type": "maintenance",
            "probability": 0.60,
            "time_to_failure": 120,
            "confidence": 0.70,
            "model_version": "pm-baseline-v2",
            "top_factors": ["firmware_age", "interface_errors"],
            "timestamp": now(),
        },
    ],
    "telemetry_windows": [
        {
            "id": "tel-001",
            "device_id": "dev-001",
            "metric_name": "cpu_usage",
            "metric_value": 45.2,
            "unit": "percent",
            "window_start": now() - timedelta(minutes=5),
            "window_end": now(),
            "timestamp": now(),
        },
        {
            "id": "tel-002",
            "device_id": "dev-001",
            "metric_name": "memory_usage",
            "metric_value": 62.8,
            "unit": "percent",
            "window_start": now() - timedelta(minutes=5),
            "window_end": now(),
            "timestamp": now(),
        },
        {
            "id": "tel-003",
            "device_id": "dev-003",
            "metric_name": "cpu_usage",
            "metric_value": 89.5,
            "unit": "percent",
            "window_start": now() - timedelta(minutes=5),
            "window_end": now(),
            "timestamp": now(),
        },
        {
            "id": "tel-004",
            "device_id": "dev-002",
            "metric_name": "throughput",
            "metric_value": 1250.0,
            "unit": "mbps",
            "window_start": now() - timedelta(minutes=5),
            "window_end": now(),
            "timestamp": now(),
        },
    ],
    "scenarios": [
        {
            "id": "scen-001",
            "name": "Network Outage Simulation",
            "description": "Estimate service impact after a core routing outage",
            "scenario_type": "disaster_recovery",
            "status": "ready",
            "created_at": now(),
            "affected_assets": ["dev-001", "dev-002"],
            "risk_score": 0.82,
        },
        {
            "id": "scen-002",
            "name": "Virtualization Host Degradation",
            "description": "Assess predictive maintenance timing for VM host instability",
            "scenario_type": "predictive_maintenance",
            "status": "ready",
            "created_at": now(),
            "affected_assets": ["dev-003"],
            "risk_score": 0.74,
        },
    ],
    "incidents": [
        {
            "id": "incident-001",
            "device_id": "dev-003",
            "title": "CPU saturation investigation",
            "severity": "medium",
            "status": "open",
            "created_at": now(),
        },
    ],
    "scenario_runs": [
        {
            "id": "scenario-run-001",
            "scenario_id": "scen-001",
            "status": "completed",
            "risk_score_before": 0.82,
            "risk_score_after": 0.51,
            "created_at": now(),
        },
    ],
    "settings": [
        {
            "id": "app",
            "project_id": "infrasight-gzu",
            "auth_provider": "firebase",
            "mock_fallback_enabled": True,
            "updated_at": now(),
        },
    ],
    "evaluation_runs": [
        {
            "id": "eval-001",
            "model_id": "pm-baseline-v2",
            "metric_name": "accuracy",
            "metric_value": 0.92,
            "dataset": "ict-maintenance-window-sample",
            "timestamp": now(),
        },
        {
            "id": "eval-002",
            "model_id": "pm-baseline-v2",
            "metric_name": "precision",
            "metric_value": 0.89,
            "dataset": "ict-maintenance-window-sample",
            "timestamp": now(),
        },
        {
            "id": "eval-003",
            "model_id": "anomaly-detector-v1",
            "metric_name": "f1_score",
            "metric_value": 0.87,
            "dataset": "telemetry-anomaly-sample",
            "timestamp": now(),
        },
    ],
}
